apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "external-dns-webhook-technitium.fullname" . }}
  labels:
    {{- include "external-dns-webhook-technitium.labels" . | nindent 4 }}
data:
  TECHNITIUM_URL: {{ .Values.technitium.url | quote }}
  LOG_LEVEL: {{ .Values.logLevel | quote }}
  LOG_FORMAT: {{ .Values.logFormat | quote }}
  {{- if .Values.technitium.domainFilter }}
  DOMAIN_FILTER: {{ join "," .Values.technitium.domainFilter | quote }}
  {{- end }}
