apiVersion: v1
kind: Secret
metadata:
  name: {{ include "external-dns-webhook-technitium.fullname" . }}
  labels:
    {{- include "external-dns-webhook-technitium.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.technitium.token }}
  TECHNITIUM_TOKEN: {{ .Values.technitium.token | quote }}
  {{- else }}
  TECHNITIUM_USERNAME: {{ .Values.technitium.username | quote }}
  TECHNITIUM_PASSWORD: {{ .Values.technitium.password | quote }}
  {{- end }}
